import { mapStringToMap } from '../util.js';

const PALLET_TOWN = `TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXTTXXTXXXXXXXXXXXXXXXT
TXXXRXXXXTXXXTXXXXXXXXXXXXXXXXXT
TXXXXXXXXXTXTXXXXWWWXXXXXXXXXXXT
TXXXXXXXXXXXXXTXXDWWXXXXXXXXXXXT
TXXTWDWTXXTXXTXXXWWWXXXXXXXXXXXT
TXXTWWWTXXXXXXTXXXXXXXXXXXXXXXXT
TXXTTTTTXXXXTXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXTXXXXXXXXXXXXXXXXXXXXT
TXXRRXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXRXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
`;

const mapStringLegend = {
  R: 'rock',
  T: 'tree',
  W: 'walls',
  O: 'water',
  X: 'ground',
  D: 'door',
};

const processedMap = mapStringToMap(PALLET_TOWN, mapStringLegend);

export const map1 = {
  ...processedMap,
  name: 'map1',
  playerStart: { x: 1, y: 1 },
  wayPoints: [
    {
      destination: 'map2',
      locations: { from: { x: 17, y: 5 }, to: { x: 16, y: 5 } },
    },
    {
      destination: 'map2',
      locations: { from: { x: 5, y: 6 }, to: { x: 5, y: 5 } },
    },
  ],
};
