import { mapStringToMap } from '../util.js';

const PALLET_TOWN = `WXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXW
WXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXW
WXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXW
WXXXXXXRXXXXXXXXXXXXXXXXXXXXXXXW
WXXXXXXRXXWXXRRXXWWWXXXXXXXXXXXW
WXXXXXXXXXWXXXXXXDWWXXOXXXXXXXXW
WXXXWDWXXXWXXXXXXWWWXXOXXXXXXXXW
WXXXWWWXXXWXWWWXXXXXXXOXXXXXXXXW
WXXXXXXXXXWXWXXXXXXOOOOXXXXXXXXW
WXXXXXXWXXXXXXXRRXXXXXXXXXXXXXXW
WXXXXXXWWWXXXXXXRRXXXXXXXXXXXXXW
WXXXXXXXXXXXXXXRXRXOOXXXXXXXXXXW
WXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXW
WXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXW
WXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXW
WXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXW
WXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
`;

const mapStringLegend = {
  R: 'rock',
  T: 'tree',
  W: 'walls',
  X: 'ground',
  O: 'water',
  D: 'door',
};

const processedMap = mapStringToMap(PALLET_TOWN, mapStringLegend);

export const map2 = {
  ...processedMap,
  name: 'map2',
  playerStart: { x: 2, y: 2 },
  //CHANGE MAP POINT LOCATION
  wayPoints: [
    {
      destination: 'map1',
      locations: { from: { x: 17, y: 5 }, to: { x: 16, y: 5 } },
    },
    {
      destination: 'map1',
      locations: { from: { x: 5, y: 6 }, to: { x: 5, y: 5 } },
    },
  ],
};
