import { mapStringToMap } from '../util.js';

const PALLET_TOWN = `TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXWWWXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXOOOXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXOOOXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXOOOXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXT
`;

const mapStringLegend = {
  R: 'rock',
  T: 'tree',
  W: 'walls',
  O: 'water',
};

const processedMap = mapStringToMap(PALLET_TOWN, mapStringLegend);

export const map2 = {
  ...processedMap,
  name: 'map2',
  playerStart: { x: 2, y: 2 },
};
