import { mapStringToMap } from '../util.js';

const TEMPLATE = `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
`;

const mapStringLegend = {
  X: 'ground',
};

const processedMap = mapStringToMap(PALLET_TOWN, mapStringLegend);

export const map2 = {
  ...processedMap,
  name: 'map2',
  playerStart: { x: 2, y: 2 },
  //CHANGE MAP POINT LOCATION
  wayPoints: [
    {
      destination: 'map1',
      locations: { from: { x: 17, y: 5 }, to: { x: 16, y: 5 } },
    },
    {
      destination: 'map1',
      locations: { from: { x: 5, y: 6 }, to: { x: 5, y: 5 } },
    },
  ],
};
